// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_DayBar;
extern lv_obj_t * ui_dayHours;
extern lv_obj_t * ui_WeekBar;
extern lv_obj_t * ui_MonthLabel;
extern lv_obj_t * ui_monthHours;
extern lv_obj_t * ui_WeekLabel;
extern lv_obj_t * ui_weekHours;
extern lv_obj_t * ui_MaxHours;
extern lv_obj_t * ui_PresentDate;
// CUSTOM VARIABLES
extern lv_obj_t * uic_dayHours;
extern lv_obj_t * uic_Month;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
