// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT Day

lv_obj_t * ui_Day_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Day;
    cui_Day = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_Day, 75);
    lv_obj_set_height(cui_Day, 30);
    lv_obj_set_x(cui_Day, -100);
    lv_obj_set_y(cui_Day, -60);
    lv_obj_set_align(cui_Day, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Day, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Day, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DAY_NUM);
    children[UI_COMP_DAY_DAY] = cui_Day;
    lv_obj_add_event_cb(cui_Day, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Day, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Day_create_hook(cui_Day);
    return cui_Day;
}

