// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_DAY_H
#define _UI_COMP_DAY_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Day
#define UI_COMP_DAY_DAY 0
#define _UI_COMP_DAY_NUM 1
lv_obj_t * ui_Day_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
